In [2]:
#Linear Regression using Gradient Descent Algorithm from scratch.
#1. It is applied on a single feature sqft_living to predict price.
    #RSS obtained for single/simple linear regression by both closed form(week 1) and Gradient Descent approach is same.
#2. The same is applied on multiple feature and RSS is obtained.   

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('kc_house_data.csv')

In [3]:
def get_np_data(data,features,output):
    data['constant']=1
    features=['constant']+features
    features_sframe=data[features]
    features_matrix=features_sframe.to_numpy()
    output_sarray=data[output]
    output_array=output_sarray.to_numpy()
    return(features_matrix,output_array)


In [4]:
def predict_outcome(features_matrix, weights):
    predictions=np.dot(features_matrix,weights)
    return(predictions)


In [5]:
def feature_derivative(errors, feature):
    derivative=2*np.dot(errors,feature)
    return(derivative)

In [6]:
def regression_gradient_descent(feature_matrix, output, initial_weights, step_size, tolerance):
    converged = False
    weights = np.array(initial_weights)
    while not converged:
        predictions=predict_outcome(feature_matrix, weights)
        errors=predictions-output
        
        
        gradient_sum_squares = 0 # initialize the gradient
        # while not converged, update each weight individually:
        for i in range(len(weights)):
            # Recall that feature_matrix[:, i] is the feature column associated with weights[i]
            feature=feature_matrix[:,i]
            # compute the derivative for weight[i]:
            derivative=feature_derivative(errors,feature)
            
            # add the squared derivative to the gradient magnitude
            gradient_sum_squares+=derivative**2
            
            # update the weight based on step size and derivative:
            weights[i] = weights[i] - (step_size * derivative)

        gradient_magnitude = (gradient_sum_squares)**0.5
        if gradient_magnitude < tolerance:
            converged = True
    return(weights)

In [7]:
train_data=pd.read_csv('kc_house_train_data.csv')
test_data=pd.read_csv('kc_house_test_data.csv')
train_data.shape

(17384, 21)

In [8]:

simple_features = ['sqft_living']
my_output= 'price'
(simple_feature_matrix, output) = get_np_data(train_data, simple_features, my_output)
initial_weights = np.array([-47000.0,-1.0])
step_size = 7e-12
tolerance = 2.5e7

In [9]:
print(simple_feature_matrix)

[[   1 1180]
 [   1 2570]
 [   1  770]
 ...
 [   1 1530]
 [   1 1600]
 [   1 1020]]


In [10]:
predict_outcome(simple_feature_matrix,initial_weights)

array([-48180., -49570., -47770., ..., -48530., -48600., -48020.])

In [11]:
output

array([221900., 538000., 180000., ..., 360000., 400000., 325000.])

In [12]:
simple_weights=regression_gradient_descent(simple_feature_matrix,output,initial_weights,step_size,tolerance)
print(simple_weights)

[-46999.88636181    281.91211866]


In [13]:
test_simple_features = ['sqft_living']
test_output= 'price'
(test_simple_feature_matrix, output) = get_np_data(test_data, test_simple_features, test_output)


In [30]:
y_predicted=predict_outcome(test_simple_feature_matrix,simple_weights)
y_predicted

array([356134.44332787, 784640.86369733, 435069.83655383, ...,
       663418.65267176, 604217.10775229, 240550.47467559])

In [16]:
R1=(output-y_predicted)**2
RSS1=np.sum(R1)

In [17]:
print(RSS1)

275400044885866.16


In [18]:
model_features = ['sqft_living', 'sqft_living15']
my_output = 'price'
(feature_matrix1, output) = get_np_data(train_data, model_features,my_output)
initial_weights = np.array([-100000.0, 1.0, 1.0])
step_size = 4e-12
tolerance = 1e9

In [19]:
predict_outcome(feature_matrix1,initial_weights)


array([-97480., -95740., -96510., ..., -96940., -96990., -97960.])

In [20]:
print(feature_matrix1)

[[   1 1180 1340]
 [   1 2570 1690]
 [   1  770 2720]
 ...
 [   1 1530 1530]
 [   1 1600 1410]
 [   1 1020 1020]]


In [21]:
print(output)


[221900. 538000. 180000. ... 360000. 400000. 325000.]


In [22]:
simple_weights2=regression_gradient_descent(feature_matrix1,output,initial_weights,step_size,tolerance)
print(simple_weights2)

[-9.99999688e+04  2.45072603e+02  6.52795267e+01]


In [23]:
test_simple_features2 = ['sqft_living','sqft_living15']
test_output= 'price'
(test_simple_feature_matrix2, output2) = get_np_data(test_data, test_simple_features2, test_output)
y_predicted2=predict_outcome(test_simple_feature_matrix2,simple_weights2)


In [24]:
y_predicted2

array([366651.41162949, 762662.39850726, 386312.09557541, ...,
       682087.39916306, 585579.27901327, 216559.20391786])

In [25]:
y_predicted2[0]

366651.4116294939

In [26]:
output2[0]

310000.0

In [28]:
R2=(output2-y_predicted2)**2
RSS2=np.sum(R2)

In [29]:
print(RSS2)

270263443629803.56
